name: Frontend build

on:
  pull_request:
    branches: ["main", "develop", "release"]
    paths: ["frontend/**"]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
